name: Lint

permissions:
  contents: write

on:
  push:
    branches: [ main, unstable ]
  pull_request:
    branches: [ main, unstable ]
  workflow_dispatch: # Permet le déclenchement manuel

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install black==23.12.1 flake8==6.1.0 isort==5.13.2
    
    - name: Run Black
      # On enlève le "|| echo" pour que l'étape échoue vraiment si le code n'est pas bon
      # run: black --check custom_components/eedomus/
      run: black  custom_components/eedomus/
    
    - name: Run isort
      if: always() # Continue même si Black a échoué
      # run: isort --check custom_components/eedomus/
      run: isort  custom_components/eedomus/
    
    - name: Run flake8
      if: always() # Continue même si Black ou isort ont échoué
      # run: flake8 custom_components/eedomus/ --max-line-length=120 --extend-ignore=E203,F401,F821,E501,E713,E714,E721,F541,F841,E402,E266,F601
      run: flake8 custom_components/eedomus/ --max-line-length=120
    
    - name: Auto-fix formatting
      if: failure() # Se déclenche uniquement si l'une des étapes précédentes a réellement échoué
      run: |
        # black custom_components/eedomus/
        # isort custom_components/eedomus/
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto-fix: Format code with black and isort"
        git push
