name: Lint

permissions:
  contents: write

on:
  push:
    branches: [ main, unstable ]
  pull_request:
    branches: [ main, unstable ]
  workflow_dispatch: # Permet le déclenchement manuel

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref || github.ref_name }}
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install black==23.12.1 flake8==6.1.0 isort==5.13.2 vulture
    
    - name: Run Black
      run: black custom_components/eedomus/
    
    - name: Run isort
      run: isort custom_components/eedomus/
    
    - name: Run flake8
      run: flake8 custom_components/eedomus/ --max-line-length=120
      
    - name: Run Vulture (Détection de code mort)
      run: vulture custom_components/eedomus/ --min-confidence 80
    
    - name: Auto-commit formatted code
      if: success() # S'exécute uniquement si toutes les étapes précédentes (Black, isort, flake8, vulture) ont réussi
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        if [[ -n "$(git status --porcelain)" ]]; then
          git add .
          git commit -m "Auto-fix: Format code with black and isort [skip ci]"
          git push
        else
          echo "No changes to commit"
        fi
